# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envioindexer
networks:
- id: 696969
  start_block: 0
  contracts:
  - name: chatsearch
    address:
    - 0x44241cd673bFDe20C31c54203F10384B40eC5F43
    handler: src/EventHandlers.ts
    events:
    - event: ChatCreated(address indexed owner, uint256 indexed chatId)
    - event: MessageAdded(uint256 indexed chatId, string role, string content)
rollback_on_reorg: false
