# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envioIndexer
networks:
- id: 696969
  start_block: 0
  contracts:
  - name: ChatSearchAI
    address:
    - 0x7D2b35E1943007F50d45E5c10F60C7F9DA6eE4E8
    handler: src/EventHandlers.ts
    events:
    - event: ChatCreated(address indexed owner, uint256 indexed chatId)
    - event: MessageAdded(uint256 indexed chatId, string role, string content)
rollback_on_reorg: false
